const en = [[{
  value: '`',
  shiftValue: '~',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '1',
  shiftValue: '!',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '2',
  shiftValue: '@',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '3',
  shiftValue: '#',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '4',
  shiftValue: '$',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '5',
  shiftValue: '%',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '6',
  shiftValue: '^',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '7',
  shiftValue: '&',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '8',
  shiftValue: '*',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '9',
  shiftValue: '(',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '0',
  shiftValue: ')',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '-',
  shiftValue: '_',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '=',
  shiftValue: '+',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'Backspace',
  shiftValue: 'Backspace',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_big',
}], [{
  value: 'Tab',
  shiftValue: 'Tab',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_small',
}, {
  value: 'q',
  shiftValue: 'Q',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'w',
  shiftValue: 'W',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'e',
  shiftValue: 'E',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'r',
  shiftValue: 'R',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 't',
  shiftValue: 'T',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'y',
  shiftValue: 'Y',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'u',
  shiftValue: 'U',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'i',
  shiftValue: 'I',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'o',
  shiftValue: 'O',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'p',
  shiftValue: 'P',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '[',
  shiftValue: '{',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: ']',
  shiftValue: '}',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '\\',
  shiftValue: '|',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'Del',
  shiftValue: 'Del',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_small',
}], [{
  value: 'CapsLock',
  shiftValue: 'CapsLock',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_big',
}, {
  value: 'a',
  shiftValue: 'A',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 's',
  shiftValue: 'S',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'd',
  shiftValue: 'D',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'f',
  shiftValue: 'F',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'g',
  shiftValue: 'G',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'h',
  shiftValue: 'H',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'j',
  shiftValue: 'J',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'k',
  shiftValue: 'K',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'l',
  shiftValue: 'L',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: ';',
  shiftValue: ':',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '\'',
  shiftValue: '"',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'Enter',
  shiftValue: 'Enter',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_big',
}], [{
  value: 'Shift',
  shiftValue: 'Shift',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_big',
}, {
  value: 'z',
  shiftValue: 'Z',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'x',
  shiftValue: 'X',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'c',
  shiftValue: 'C',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'v',
  shiftValue: 'V',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'b',
  shiftValue: 'B',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'n',
  shiftValue: 'N',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: 'm',
  shiftValue: 'M',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: ',',
  shiftValue: '<',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '.',
  shiftValue: '>',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '/',
  shiftValue: '?',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_symbol',
}, {
  value: '↑',
  shiftValue: '↑',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_small',
}, {
  value: 'Shift',
  shiftValue: 'Shift',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_big',
}], [{
  value: 'Ctrl',
  shiftValue: 'Ctrl',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_small',
}, {
  value: 'Win',
  shiftValue: 'Win',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_small',
}, {
  value: 'Alt',
  shiftValue: 'Alt',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_small',
}, {
  value: ' ',
  shiftValue: ' ',
  comand: [],
  symbolic: true,
  class: 'keyboard__btn keyboard__btn_space',
}, {
  value: 'Alt',
  shiftValue: 'Alt',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_small',
}, {
  value: '←',
  shiftValue: '←',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_small',
}, {
  value: '↓',
  shiftValue: '↓',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_small',
}, {
  value: '→',
  shiftValue: '→',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_small',
}, {
  value: 'Ctrl',
  shiftValue: 'Ctrl',
  comand: [],
  symbolic: false,
  class: 'keyboard__btn keyboard__btn_comand_small',
}]];
